### ISSUE TITLE
Problems with gateway.sendPacket on BungeeCord

### ISSUE THREAD

**Issue by JBou** [keir-nellyer/PluginMessageFramework#2]
I just tried the documentation on [this](https://github.com/iKeirNez/PluginMessageFramework/blob/master/pmf-bungeecord/README.md) page to send a plugin message from Bungeecord to Spigot, but it doesn't arrive. Am I doing something wrong? I did it exactly like there! This is the method I used:

``` java
gateway.sendPacket(proxiedPlayer, new MyPacket(myPacket.getMessage().toUpperCase()));
```

I have tried for hours to fix it and looked at the documentation, but nothing worked. Then I finally looked into the source code and saw that you are calling 

``` java
connection.sendData(channel, bytes);
```

right [here](https://github.com/iKeirNez/PluginMessageFramework/blob/771363f767686dd2998c34b17f7a71f569b6d207/pmf-bungeecord/src/main/java/com/ikeirnez/pluginmessageframework/bungeecord/BungeeGateway.java#L37). I think the problem is, that the plugin message is being send to the client using this method.

Now I use:

``` java
 gateway.sendPacketServer(proxiedPlayer.getServer().getInfo(), new MyPacket(myPacket.getMessage().toUpperCase()));
```

which is working fine, except that the player who executes the command isn't the same as the player parameter on the PacketHandler method, because it uses a random / the first player on the server to send the plugin message.

So is there a possibility to add a feature like Side.CLIENT and Side.SERVER to specify to which side the plugin message should be send and it send it then to spigot using the specified server? for example:

``` java
gateway.sendPacket(proxiedPlayer, new MyPacket(myPacket.getMessage().toUpperCase()), Side.SERVER); //send to server the proxiedplayer is connected to
gateway.sendPacket(proxiedPlayer, new MyPacket(myPacket.getMessage().toUpperCase()), Side.CLIENT); //send to client
```

**Comment by keir-nellyer** [comment]
~~This has already kinda been implemented, depending on what **ProxySide** you use [here](https://github.com/iKeirNez/PluginMessageFramework/blob/master/pmf-bungeecord/src/main/java/com/ikeirnez/pluginmessageframework/bungeecord/BungeeGatewayProvider.java#L22), it will either be sent to the client or the server.~~

~~Let me know if this helps :)~~

Actually I see what you mean now, will fix that!

**Comment by keir-nellyer** [comment]
Fixed! :)

It will now obey the ProxySide set here: https://github.com/iKeirNez/PluginMessageFramework/blob/master/pmf-bungeecord/src/main/java/com/ikeirnez/pluginmessageframework/bungeecord/BungeeGatewayProvider.java#L22

**Comment by JBou** [comment]
Thank you really much! :+1: After three days of testing it's finally working :D But if I set the ProxySide to SERVER, can I send a pluginmessage to the client and to Bukkit, or only to Bukkit?

**Comment by keir-nellyer** [comment]
Haha your welcome :) glad it's sorted now! 

Currently that's not possible by design, but you can create another gateway to listen on the client side?

**Comment by JBou** [comment]
Oh yes, thats true. Thanks :) Only for my interest, are you planning something like a forge or liteloader implementation to send plugin messages from the clientside?

**Comment by keir-nellyer** [comment]
I did plan to do that, however I've never used Forge or liteloader in the past so I'd need to wait til I had more free time to implement those.

However if you wish to, you could send a PR for those implementations? :D

**Comment by JBou** [comment]
Ok, me too. But If i need it later on I will take a look at it :)

**Comment by keir-nellyer** [comment]
Okay, awesome :)
